#define ENG_0 "&About...\ta"
#define ENG_1 "&Keyboard shortcuts\tF1"
#define ENG_2 "Select &target...\tt"
#define ENG_3 "&Control...\tc"
#define ENG_4 "&Unlimit all\tu"
#define ENG_5 "&Unlimit all"
#define ENG_6 "&Real-time mode"
#define ENG_7 "&Write log"
#define ENG_8 "&Watch...\tw"
#define ENG_9 "U&nwatch"
#define ENG_10 "&Visit homepage"
#define ENG_11 "&Online help"

#define FRE_0 "&A propos de...\ta"
#define FRE_1 "&Raccourcis clavier\tF1"
#define FRE_2 "&Selection Processus (Target)...\tt"
#define FRE_3 "&Taux de limitation (Control)...\tc"
#define FRE_4 "&Ne plus rien limiter\tu"
#define FRE_5 "&Ne plus rien limiter"
#define FRE_6 "&Mode temps réel"
#define FRE_7 "Ecrire &historique"
#define FRE_8 "Surveiller (&Watch)...\tw"
#define FRE_9 "N&e plus surveiller"
#define FRE_10 "&Page de présentation (Anglais)"
#define FRE_11 "A&ides en ligne (Anglais)"
#define FRE_12 "&Materia"
#define FRE_13 "&SSP"
#define FRE_14 "&CROW"
#define FRE_15 "&Ghost Center"


#define ENG_12 "&Materia"
#define ENG_13 "&SSP"
#define ENG_14 "&CROW"
#define ENG_15 "&Ghost Center"
#define ENG_16 "&Chinese (Simplified)"
#define ENG_17 "Chinese (&Traditional)"
#define ENG_18 "&English"
#define ENG_19 "&Finnish"
#define ENG_20 "F&rench"
#define ENG_21 "&Japanese"
#define ENG_22 "&Spanish"
#define ENG_23 "&Yamato-kotoba"
#define ENG_24 "&Restore BES" //****
#define ENG_25 "E&xit\tx"
#define ENG_26 "E&xit" //****
#define ENG_27 "Exit &anyway\tCtrl+F9"
#define ENG_28 "&Snap"
#define ENG_29 "&Language"
#define ENG_30 "&Ukagaka"

#define FRE_16 "&Chinois (Simplifié)"
#define FRE_17 "Chinois (&Traditionnel)"
#define FRE_18 "&Anglais (English)"
#define FRE_19 "&Finnois"
#define FRE_20 "F&rançais"
#define FRE_21 "&Japonais"
#define FRE_22 "&Espagnol"
#define FRE_23 "&Yamato-kotoba"

#define FRE_24 "&Restaurer BES"
#define FRE_25 "&Quitter\tx"
#define FRE_26 "&Quitter"
#define FRE_27 "Quitter (&forcer)\tCtrl+F9"
#define FRE_28 "&Capture d'état"
#define FRE_29 "&Langue"
#define FRE_30 "&Ukagaka"

#define FIN_0 "&Tietoa ohjelmasta...\ta"
#define FIN_1 "&Pikavalinnat\tF1"
#define FIN_2 "&Valitse kohdeprosessi...\tt"
#define FIN_3 "&Tarkastaja...\tc"
#define FIN_4 "&Lopeta kaikki rajoittaminen\tu"
#define FIN_5 "&Lopeta kaikki rajoittaminen" //****
#define FIN_6 "&Real-time modo"
#define FIN_7 "&Kirjaa lokiin"
#define FIN_8 "&Katsella...\tw"
#define FIN_9 "L&opeta katseleminen"
#define FIN_10 "&Kotisivu"
#define FIN_11 "&Online-ohje"
#define FIN_12 "&Materia"
#define FIN_13 "&SSP"
#define FIN_14 "&CROW"
#define FIN_15 "&Ghost Center"
#define FIN_16 "&kiina (Simplified)"
#define FIN_17 "kiina (&Traditional)"
#define FIN_18 "&englanti (English)"
#define FIN_19 "&suomi"
#define FIN_20 "&ranska"
#define FIN_21 "&japani"
#define FIN_22 "e&spanja"
#define FIN_23 "&Yamato-kotoba"
#define FIN_24 "&Palauta BES:n" //****
#define FIN_25 "&Lopeta ohjelma\tx"
#define FIN_26 "&Lopeta ohjelma" //****
#define FIN_27 "L&opeta joka tapaukusessa\tCtrl+F9"
#define FIN_28 "&Snapshot"
#define FIN_29 "k&ieli (language)"
#define FIN_30 "&Ukagaka"

#define JPN_0 "バージョン情報 (&A)\ta"
#define JPN_1 "ショートカット (&K)\tF1"
#define JPN_2 "ターゲット選択... (&T)\tt"
#define JPN_3 "制限率... (&C)\tc"
#define JPN_4 "制限を解除 (&U)\tu"
#define JPN_5 "制限を解除 (&U)"
#define JPN_6 "リアルタイム・モード (&R)"
#define JPN_7 "デバッグログ出力 (&W)"
#define JPN_8 "監視... (&W)\tw"
#define JPN_9 "監視を中止 (&N)"
#define JPN_10 "ホームページ (&V)"
#define JPN_11 "オンラインヘルプ (&O)"
#define JPN_12 "&Materia"
#define JPN_13 "&SSP"
#define JPN_14 "&CROW"
#define JPN_15 "何かゴーストセンター (&G)"
#define JPN_16 "中国語（簡体字） (&C)"
#define JPN_17 "中国語（繁体字） (&T)"
#define JPN_18 "英語 (&English)"
#define JPN_19 "フィンランド語 (&F)"
#define JPN_20 "フランス語 (&R)"
#define JPN_21 "日本語 (&J)"
#define JPN_22 "スペイン語 (&S)"
#define JPN_23 "ヤマト言葉 (&Y)"
#define JPN_24 "ウィンドウを表示 (&R)"
#define JPN_25 "終了 (&X)\tx"
#define JPN_26 "終了 (&X)"
#define JPN_27 "制限中でも構わず終了 (&A)\tCtrl+F9"
#define JPN_28 "スナップをファイルに保存 (&S)"
#define JPN_29 "言語 (language) (&L)"
#define JPN_30 "伺か (&U)"
#define SPA_0 "&Acerca...\ta"
#define SPA_1 "Accesos &directos\tF1"
#define SPA_2 "&Seleccionar objetivo...\tt"
#define SPA_3 "&Control...\tc"
#define SPA_4 "&Ilimitar todo\tu"
#define SPA_5 "&Ilimitar todo"
#define SPA_6 "&Modo en tiempo-real"
#define SPA_7 "&Escribir registro"
#define SPA_8 "&Observar...\tw"
#define SPA_9 "&Desobservar"
#define SPA_10 "&Visitar pagina principal"
#define SPA_11 "Ayuda en &línea"
#define SPA_12 "&Materia"
#define SPA_13 "&SSP"
#define SPA_14 "&CROW"
#define SPA_15 "&Ghost Center"
#define SPA_16 "&Chino (Simplificado)"
#define SPA_17 "Chino (&Tradicional)"
#define SPA_18 "&Ingles (English)"
#define SPA_19 "&Finlandés"
#define SPA_20 "F&rancés"
#define SPA_21 "&Japonés"
#define SPA_22 "&Español"
#define SPA_23 "&Yamato-kotoba"
#define SPA_24 "&Restaurar BES"
#define SPA_25 "&Salir\tx"
#define SPA_26 "&Salir"
#define SPA_27 "Salir de todas &formas\tCtrl+F9"
#define SPA_28 "&Captura"
#define SPA_29 "&Lenguaje (language)"
#define SPA_30 "&Ukagaka"

#define CHT_0 "關於 (&A)\ta"
#define CHT_1 "捷徑 (&K)\tF1"
#define CHT_2 "選擇目標... (&T)\tt"
#define CHT_3 "限制率... (&C)\tc"
#define CHT_4 "解除所有限制 (&U)\tu"
#define CHT_5 "解除所有限制 (&U)"
#define CHT_6 "即時模式 (&R)"
#define CHT_7 "寫入記錄檔 (&W)"
#define CHT_8 "監視... (&W)\tw"
#define CHT_9 "停止監視 (&N)"
#define CHT_10 "參訪首頁 (&V)"
#define CHT_11 "線上說明 (&O)"
#define CHT_12 "&Materia"
#define CHT_13 "&SSP"
#define CHT_14 "&CROW"
#define CHT_15 "&Ghost Center"
#define CHT_16 "簡體中文 (&S)"
#define CHT_17 "繁體中文 (&T)"
#define CHT_18 "英文 (&English)"
#define CHT_19 "芬蘭語 (&F)"
#define CHT_20 "法語 (&R)"
#define CHT_21 "日文 (&J)"
#define CHT_22 "西班牙語 (&P)"
#define CHT_23 "ヤマト言葉 (&Y)"
#define CHT_24 "還原視窗 (&R)"
#define CHT_25 "結束 (&X)\tx"
#define CHT_26 "結束 (&X)"
#define CHT_27 "即使限制中也結束 (&A)\tCtrl+F9"
#define CHT_28 "儲存快照 (&S)"
#define CHT_29 "語言 (language) (&L)"
#define CHT_30 "偽春菜 (&U)"

#define CHS_0 "关于 (&A)\ta"
#define CHS_1 "快捷方式 (&K)\tF1"
#define CHS_2 "选择目标... (&T)\tt"
#define CHS_3 "限制率... (&C)\tc"
#define CHS_4 "解除所有限制 (&U)\tu"
#define CHS_5 "解除所有限制 (&U)"
#define CHS_6 "实时模式 (&R)"
#define CHS_7 "写入记录档 (&W)"
#define CHS_8 "监视... (&W)\tw"
#define CHS_9 "停止监视 (&N)"
#define CHS_10 "参观主页 (&V)"
#define CHS_11 "在线帮助 (&O)"
#define CHS_12 "&Materia"
#define CHS_13 "&SSP"
#define CHS_14 "&CROW"
#define CHS_15 "&Ghost Center"
#define CHS_16 "简体中文 (&S)"
#define CHS_17 "繁体中文 (&T)"
#define CHS_18 "英语 (&English)"
#define CHS_19 "芬兰语 (&F)"
#define CHS_20 "法语 (&R)"
#define CHS_21 "日语 (&J)"
#define CHS_22 "西班牙语 (&P)"
#define CHS_23 "ヤマト言葉 (&Y)"
#define CHS_24 "还原窗口 (&R)"
#define CHS_25 "结束 (&X)\tx"
#define CHS_26 "结束 (&X)"
#define CHS_27 "即使限制中也结束 (&A)\tCtrl+F9"
#define CHS_28 "保存快照 (&S)"
#define CHS_29 "语言 (language) (&L)"
#define CHS_30 "伪春菜 (&U)"

#define S_MENU_FIN0 "&Tiedosto"
#define S_MENU_FIN1 "T&ee"
#define S_MENU_FIN2 "&Asetukset"
#define S_MENU_FIN3 "&Ohje"
#define S_TOOLTIP_FIN0 "Valitse kohdeprosessi"
#define S_TOOLTIP_FIN1 "Lopeta kaikki rajoittaminen"
#define S_TOOLTIP_FIN2 "Hallitse prosessien rajoittamisen määrää"
#define S_TOOLTIP_FIN3 "Lopeta ohjelma"

#define S_MENU_JPN0 "ファイル(&F)"
#define S_MENU_JPN1 "実行(&D)"
#define S_MENU_JPN2 "オプション(&O)"
#define S_MENU_JPN3 "ヘルプ(&H)"
#define S_MENU_SPA0 "&Archivo"
#define S_MENU_SPA1 "&Hacer"
#define S_MENU_SPA2 "&Opciones"
#define S_MENU_SPA3 "A&yuda"

#define S_MENU_FRE0 "&Fichier"
#define S_MENU_FRE1 "&Action	"
#define S_MENU_FRE2 "&Options"
#define S_MENU_FRE3 "A&ide"


#define S_MENU_CHI0T "檔案(&F)"
#define S_MENU_CHI0S "文件(&F)"
#define S_MENU_CHI1T "執行(&D)"
#define S_MENU_CHI1S "运行(&D)"
#define S_MENU_CHI2T "選項(&O)"
#define S_MENU_CHI2S "选项(&O)"
#define S_MENU_CHI3T "說明(&H)"
#define S_MENU_CHI3S "帮助(&H)"

#define S_TOOLTIP_JPN0 "どのプロセスを制限するか選択"
#define S_TOOLTIP_JPN1 "すべての制限を解除"
#define S_TOOLTIP_JPN2 "制限の割合などを調整"
#define S_TOOLTIP_JPN3 "プログラムを終了"
#define S_TOOLTIP_FRE0 "Selectionner le processus cible (Target)"
#define S_TOOLTIP_FRE1 "Interrompre totalement les limitations."
#define S_TOOLTIP_FRE2 "Définir le taux de limitation du processus."
#define S_TOOLTIP_FRE3 "Quitter le programme."


#define S_TOOLTIP_SPA0 "Seleccionar el proceso designado"
#define S_TOOLTIP_SPA1 "Dejar de limitar totalmente"
#define S_TOOLTIP_SPA2 "Controlar cuanto limitar el proceso"
#define S_TOOLTIP_SPA3 "Terminar el programa"

#define S_TOOLTIP_CHI0T "選擇目標進程"
#define S_TOOLTIP_CHI0S "选择目标进程"
#define S_TOOLTIP_CHI1T "完全停止限制"
#define S_TOOLTIP_CHI1S "完全停止限制"
#define S_TOOLTIP_CHI2T "控制進程的限制率"
#define S_TOOLTIP_CHI2S "控制进程的限制率"
#define S_TOOLTIP_CHI3T "結束此程式"
#define S_TOOLTIP_CHI3S "结束此程序"

#define S_FIN_0001 "suomi"
#define S_FIN_1000 "Mitä prosessia haluat rajoittaa?"
#define S_FIN_1001 "Vahvistus"
#define S_FIN_2000 "Prosessorin käytön rajoittaminen"
#define S_FIN_9000 "Tietoa ohjelmasta"
#define S_FIN_DESC "...rajoittaa prosessikohtaista prosessorin käyttöä."

#define S_JPN_0001 "日本語"
#define S_JPN_1000 "どのプロセスを制限しますか?"
#define S_JPN_1001 "確認"
#define S_JPN_1002 "制限率の調整"
#define S_JPN_2000 "CPU負荷を制限中"


#define S_FRE_0001 "Français"
#define S_FRE_1000 "Quel processus (Target) souhaitez-vous limiter?"
#define S_FRE_1001 "Confirmation"
#define S_FRE_1002 "Taux de limitation de l'utilisation CPU appliqués aux processus en cours..."
#define S_FRE_2000 "Limitation de charge CPU en cours (Target #) :"


#define S_SPA_0001 "español"
#define S_SPA_1000 "¿Cual proceso desea limitar?"
#define S_SPA_1001 "Confirmación"
#define S_SPA_1002 "Limitando el uso del CPU..."
#define S_SPA_2000 "Seleccionar el proceso designado"

#define S_JPNo_0001 "ヤマト言葉"
#define S_JPNo_1000 "ターゲットスコープオープン"
#define S_JPNo_1001 "最終セーフティー解除"
#define S_JPNo_1002 "電影クロスゲージ 明度"
#define S_JPNo_2000 "CPU負荷を制限中"

#define S_CHI_0001T "繁體中文"
#define S_CHI_0001S "简体中文"
#define S_CHI_1000T "您想要限制哪個進程？"
#define S_CHI_1000S "您想要限制哪个进程？"
#define S_CHI_1001T "確認"
#define S_CHI_1001S "确认"
#define S_CHI_2000T "限制 CPU 使用率..."
#define S_CHI_2000S "限制 CPU 使用率..."


#define S_JPN_9000 "このプログラムについて"
#define S_JPN_DESC "\r\nプロセスごとのCPU使用率を制限します。"
#define S_SPA_9000 "Acerca de este programa"
#define S_SPA_DESC "Este programa limita el uso del CPU para un proceso."

#define S_FRE_9000 "A propos de ce programme"
#define S_FRE_DESC "Ce programme limite l'utilisation du CPU pour un processus défini (Target).\r\n< French by otax38>"

#define S_CHI_9000T "關於本程式"
#define S_CHI_9000S "关于本程序"	
#define S_CHI_DESC_T "本程式限制進程的 CPU 使用率。\r\n< 繁體中文 by 琥珀 >"
#define S_CHI_DESC_S "本程序限制进程的 CPU 使用率。\r\n< 简体中文 by 琥珀 >"
	
#define S_ENG_DESC TEXT( "\r\nControls per-process CPU usage." )

#define S_FIN_EXIT_ANYWAY "BES on aktiivinen. Ohjelmasta poistuminen on vaarallista.\r\n\r\nHaluatko silti poistua?"
#define S_JPN_EXIT_ANYWAY "BESは他のプログラムを制限中です。制限をきちんと解除せず終了するのは危険です。\r\n\r\n構わず終了しますか?"
#define S_FRE_EXIT_ANYWAY "BES est actif. Quitter maintenant est risquer. Quitter quand même?"
#define S_SPA_EXIT_ANYWAY "BES esta activo. Salir ahora puede ser peligroso.\r\n\r\n¿Desea salir de todas formas?"
#define S_CHI_EXIT_ANYWAY_T "BES 作用中。現在結束有危險。\r\n\r\n無論如何都要結束？"
#define S_CHI_EXIT_ANYWAY_S "BES 作用中。现在结束有危险。\r\n\r\n无论如何都要结束？"
#define S_FORMAT1_ASC "[ %s ]\r\n\r\nFile Name: %s\r\n\r\nWindow Text: %s\r\n\r\nProcess ID: 0x%04X %04X\r\n\
including %u thread"

#define S_QUESTION1_ASC "BES will limit the CPU usage for the following process.\r\n\r\nContinue?"
#define S_QUESTION2_ASC "BES will limit the CPU usage for the following process, and will keep watching this file even after the process is terminated.\
\r\n\r\nContinue?"
#define S_QUESTION1_FRE "BES limitera l'utilisation du CPU pour le processus suivant. Confirmer ?"
#define S_QUESTION2_FRE "BES limitera l'utilisation du CPU pour le processus suivant, et continuera de surveillerle fichier EXE après que le processus en cours soit terminé. Confirmer ?"

#define S_QUESTION1_SPA "BES limitara el uso del CPU para el siguiente proceso.\r\n\r\n¿Desea continuar?"
#define S_QUESTION2_SPA "BES limitara el uso del CPU del siguiente proceso, y se mantendrá observando el archivo EXE aun después de que el proceso sea terminado.\r\n\r\n¿Desea continuar?"

#define S_QUESTION1_CHIT "將要限制以下進程的 CPU 使用率。\r\n\r\n繼續？"
#define S_QUESTION1_CHIS "将要限制以下进程的 CPU 使用率。\r\n\r\n继续？"
#define S_QUESTION2_CHIT "將要限制以下進程的 CPU 使用率，並且會持續監視此執行檔，即使此進程已經結束。\r\n\r\n繼續？"
#define S_QUESTION2_CHIS "將要限制以下進程的 CPU 使用率，並且會持續監視此執行檔，即使此進程已經結束。\r\n\r\n繼續？"

#define S_FORMAT2_ASC "EXE file: %s\r\n\r\nProcess ID: 0x%04X %04X\r\n\r\nWindow Text: %s"

#define S_QUESTION1_FIN "BES rajoittaa prosessorin käyttöä seuraavalle prosessille.\r\n\r\nHaluatko jatkaa?"
#define S_QUESTION2_FIN "BES rajoittaa prosessorin käyttöä seuraavalle prosessille, ja jatkaa tämän EXE-tiedoston tarkkailua vaikka prosessi lopetettaisiinkin.\r\n\r\nHaluatko jatkaa?"


#define S_FORMAT1_JPN "[ %s ]\r\n\r\n実行ファイル名 : %s\r\n\r\nウィンドウタイトル : %s\r\n\r\nプロセスID : 0x%04X %04X\r\n\
このプロセスは以下の%u個のスレッドを含んでいます"
#define S_QUESTION1_JPN "次のプロセスのCPU負荷を制限します。\r\n\r\n制限はいつでも解除でき、制限率はパーセント単位で調整できます。\r\n\r\n開始しますか?"
#define S_QUESTION2_JPN "次のプロセスのCPU負荷を制限し、プロセス終了後も実行ファイルを監視、再起動すれば制限を実行します。\r\n\r\n続行しますか?"
#define S_FORMAT2_JPN "実行ファイル : %s\r\n\r\nプロセスID : 0x%04X %04X\r\n\r\nウィンドウタイトル : %s"



#define S_JPN_GPL "このプログラムは、GPLソフトです。\
ライセンスに従う限り、自由に再配布・改変を行うことができます。\r\n\
\r\n\
このプログラムは、無保証です。\r\n\r\n詳しくは同梱の\
 GNU General Public License を見てください。"

#define TEXT_GPL TEXT( "This program is free software; you can redistribute it and/or\
 modify it under the terms of the GNU General Public License\
 Version 2 as published by the Free Software Foundation.\r\n\
\r\n\
This program is distributed in the hope that it will be useful,\
 but WITHOUT ANY WARRANTY; without even the implied warranty of\
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\
 GNU General Public License Version 2 for more details.\r\n\r\n\r\n" )


// for SSTP - CROW doesn't like UTF-8, so for now we use SJIS
#define S_ABOUT_UTF8 "★ バトル エンコーダー シラセのバージョン情報"
