((:LABEL @INIT)
(:MOVE R 0)
(:LABEL @etat0)
(:INCR PTR)
(:LOAD R0 *PTR)
(:CMP R0 L)
(:JEQ @etat1)
(:CMP R0 E)
(:JEQ @echec)
(:CMP R0 A)
(:JEQ @echec)
(:CMP R0 $)
(:JEQ @echec)
(:JMP @echec)
(:LABEL @etat1)
(:INCR PTR)
(:LOAD R0 *PTR)
(:CMP R0 L)
(:JEQ @echec)
(:CMP R0 E)
(:JEQ @etat2)
(:CMP R0 A)
(:JEQ @etat3)
(:CMP R0 $)
(:JEQ @echec)
(:JMP @echec)
(:LABEL @etat2)
(:INCR PTR)
(:LOAD R0 *PTR)
(:CMP R0 L)
(:JEQ @echec)
(:CMP R0 E)
(:JEQ @echec)
(:CMP R0 A)
(:JEQ @echec)
(:CMP R0 $)
(:JEQ @fin)
(:JMP @echec)
(:LABEL @etat3)
(:INCR PTR)
(:LOAD R0 *PTR)
(:CMP R0 L)
(:JEQ @echec)
(:CMP R0 E)
(:JEQ @echec)
(:CMP R0 A)
(:JEQ @echec)
(:CMP R0 $)
(:JEQ @fin)
(:JMP @echec)
(:LABEL @fin)
(:MOVE R 1)
(:STOP)
(:LABEL @echec)
(:MOVE R 0)
(:STOP))
